### ISSUE TITLE
Uncompressed NBT supported

### ISSUE THREAD

**Issue by BM5k** [xxx/nbt_utils#2]
Trying to read an uncompressed nbt gives `Zlib::GzipFile::Error: not in gzip format`

**Comment by xxx** [comment]
Do they use uncompressed nbts now? I haven't kept up to date. The fix is easy enough I guess.

**Comment by BM5k** [comment]
IIRC the map data files aren’t compressed.

**Comment by xxx** [comment]
This is resolved now. thanks for the heads up!
